// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9nOFo3DuDMksnTBtdKCgwS7LCLXwk4I',
    appId: '1:475088015638:web:420b0f19c1160f2127c037',
    messagingSenderId: '475088015638',
    projectId: 'freshers-8af04',
    authDomain: 'freshers-8af04.firebaseapp.com',
    storageBucket: 'freshers-8af04.firebasestorage.app',
    measurementId: 'G-JLHXE9M2GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZ9cv3b7OghpRmDEyuU01JybgKuwcVIU',
    appId: '1:475088015638:android:e0cd56cbc7bd64c327c037',
    messagingSenderId: '475088015638',
    projectId: 'freshers-8af04',
    storageBucket: 'freshers-8af04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1AU0r7nKGMOfVxRLFH_R5TBBXggkArU',
    appId: '1:475088015638:ios:350ed7f49de0ba8927c037',
    messagingSenderId: '475088015638',
    projectId: 'freshers-8af04',
    storageBucket: 'freshers-8af04.firebasestorage.app',
    iosBundleId: 'com.example.freshers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1AU0r7nKGMOfVxRLFH_R5TBBXggkArU',
    appId: '1:475088015638:ios:350ed7f49de0ba8927c037',
    messagingSenderId: '475088015638',
    projectId: 'freshers-8af04',
    storageBucket: 'freshers-8af04.firebasestorage.app',
    iosBundleId: 'com.example.freshers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT9nOFo3DuDMksnTBtdKCgwS7LCLXwk4I',
    appId: '1:475088015638:web:929613a0a41e4e0127c037',
    messagingSenderId: '475088015638',
    projectId: 'freshers-8af04',
    authDomain: 'freshers-8af04.firebaseapp.com',
    storageBucket: 'freshers-8af04.firebasestorage.app',
    measurementId: 'G-W9XY6Q8FR8',
  );
}
